export const mode = {
  DEFAULT: 'DEFAULT',
  POST_DETAIL: 'POST_DETAIL',
  CREATE_POST: 'CREATE_POST'
}

export const sort = {
  DEFAULT: 'DEFAULT',
  HIGH_SCORE: 'DESCENDING ORFER BY THE SCORE',
  LOW_SCORE: 'ASCENDING ORFER BY THE SCORE',
  NEW_POST: 'FROM NEWEST TO OLDEST',
  OLD_POST: 'FROM OLDEST TO NEWEST'
}
